### ISSUE TITLE
PowerSimulations 0.27.6 breaks HydroPowerSimulations test environment.

### ISSUE THREAD

**Issue by pesap** [NREL-Sienna/PowerSimulations.jl#1089]
**Describe the bug**
The REPL says that `fast_ipopt_optimizer` is not defined.

**Screenshots**

![image](https://github.com/NREL-Sienna/PowerSimulations.jl/assets/2238996/cae7dfec-f8b5-4e7a-98a2-1f3e747f8ec9)

![image](https://github.com/NREL-Sienna/PowerSimulations.jl/assets/2238996/2bca0620-ea99-4084-815a-3bd6b5d90b18)

**Additional context**
Downgrading to PowerSimulations 0.27.5  works

**Comment by jd-lara** [comment]
This is a problem in your environment. I can't reproduce.

**Comment by pesap** [comment]
Closing this since it was a bug in HPS.

Related:
- https://github.com/NREL-Sienna/HydroPowerSimulations.jl/pull/31
