### ISSUE TITLE
Duals all NaN when including ReserveDemandCurve

### ISSUE THREAD

**Issue by Nongchao** [NREL-Sienna/PowerSimulations.jl#1093]
When including `PSY.ReserveDemandCurve` in `ProblemTemplate`, the problem solves, but the duals are all `NaN`.

**Comment by jd-lara** [comment]
@sourabhdalvi Do you call what the implementation of ReserveDemandCurve looks like?

**Comment by Nongchao** [comment]
> @sourabhdalvi Do you call what the implementation of ReserveDemandCurve looks like?

Sourabh helped me figured out what's causing the issue. Essentially SOS variables were introduced and my understanding is there's no way to fix these variables to solve a LP to get duals. But in my application, SOS variables are not needed, so we had a "hacky" way to by-pass the convexity check and not introducing SOS variables for now.

**Comment by jd-lara** [comment]
@Nongchao I'd be good to know what you are doing to make sure that we can incorporate the fix you are using.

**Comment by jd-lara** [comment]
closing since it can't be replicated. @rodrigomha we need a test with the new ORCD to recover Duals
