### ISSUE TITLE
`UndefVarError` in `construct_device!` 

### ISSUE THREAD

**Issue by GabrielKS** [NREL-Sienna/PowerSimulations.jl#1175]
In released code, this line:
https://github.com/NREL-Sienna/PowerSimulations.jl/blob/4218c87b92d74bfa09bce209db1ee5d39f821c06/src/devices_models/device_constructors/branch_constructor.jl#L1040
causes ```UndefVarError: `devices` not defined```. Seems very likely to be a copypaste error, suggesting a refactor to remove code duplication might be beneficial.

**Comment by jd-lara** [comment]
requires adding this call 
```
devices = get_available_components(model, sys)
```
