### ISSUE TITLE
TransmissionInterface direction type should be Float instead of Int

### ISSUE THREAD

**Issue by mvivienneliu** [NREL-Sienna/PowerSimulations.jl#1203]
**If this is a question, something isn't working or an idea please start a Q&A discussion in the [Discussion tab](https://github.com/NREL-Sienna/PowerSimulations.jl/discussions)**
Open a bug report only if you can provide the details below

**Describe the bug**
I have a problem with PSY TransmissionInterface, the get_direction_mapping would return a Dict(String,Int64)
PSY.get_direction_mapping
  get_direction_mapping(
      value::TransmissionInterface
  ) -> Dict{String, Int64}
But in PSI, when we try to _add_to_jump_expression!, the multiplier has to be a Float64 (which is direction here) so it always return an error.
**To Reproduce**
Paste the code we can run to reproduce the error you are seeing

**Expected behavior**

**Screenshots**

**Additional context**
┌ Error: Simulation build failed
│   exception =
│    MethodError: no method matching _add_to_jump_expression!(::AffExpr, ::VariableRef, ::Int64)
│    
│    Closest candidates are:
│      _add_to_jump_expression!(::T, ::VariableRef, ::Float64, ::Float64) where T<:AbstractJuMPScalar
│       @ PowerSimulations ~/.julia/packages/PowerSimulations/2yc8E/src/devices_models/devices/common/add_to_expression.jl:110
│      _add_to_jump_expression!(::T, ::VariableRef, ::Float64) where T<:AbstractJuMPScalar
│       @ PowerSimulations ~/.julia/packages/PowerSimulations/2yc8E/src/devices_models/devices/common/add_to_expression.jl:93
│      _add_to_jump_expression!(::T, ::Float64, ::Float64) where T<:AbstractJuMPScalar
│       @ PowerSimulations ~/.julia/packages/PowerSimulations/2yc8E/src/devices_models/devices/common/add_to_expression.jl:121
│      ...
│    
│    Stacktrace:
│      [1] add_to_expression!(container::PowerSimulations.OptimizationContainer, ::Type{PowerSimulations.InterfaceTotalFlow}, ::Type{FlowActivePowerVariable}, service::TransmissionInterface, model::ServiceModel{TransmissionInterface, ConstantMaxInterfaceFlow})
│        @ PowerSimulations ~/.julia/packages/PowerSimulations/2yc8E/src/devices_models/devices/common/add_to_expression.jl:1301
│      [2] construct_service!(container::PowerSimulations.OptimizationContainer, sys::System, ::InfrastructureSystems.Optimization.ModelConstructStage, model::ServiceModel{TransmissionInterface, ConstantMaxInterfaceFlow}, devices_template::Dict{Symbol, DeviceModel}, incompatible_device_types::Set{DataType}, network_model::NetworkModel{PTDFPowerModel})
│        @ PowerSimulations ~/.julia/packages/PowerSimulations/2yc8E/src/services_models/services_constructor.jl:569
│      [3] construct_services!(container::PowerSimulations.OptimizationContainer, sys::System, stage::InfrastructureSystems.Optimization.ModelConstructStage, services_template::Dict{Tuple{String, Symbol}, ServiceModel}, devices_template::Dict{Symbol, DeviceModel}, network_model::NetworkModel{PTDFPowerModel})
│        @ PowerSimulations ~/.julia/packages/PowerSimulations/2yc8E/src/services_models/services_constructor.jl:74
│      [4] macro expansion
│        @ ~/.julia/packages/PowerSimulations/2yc8E/src/core/optimization_container.jl:739 [inlined]

**Comment by jd-lara** [comment]
closed via #1205
