### ISSUE TITLE
export PNM methods

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL-Sienna/PowerSimulations.jl#975]
With the seperation of PSY and PNM, the `PTDF` methods aren't available without explicitly including PNM. Since it's common to need the ptdf when running simulations, I think it would be useful to reexport some of the PNM methods in PSI.

**Comment by jd-lara** [comment]
which methods?

**Comment by claytonpbarrows** [comment]
`PTDF`

**Comment by claytonpbarrows** [comment]
and maybe `VirtualPTDF`

**Comment by jd-lara** [comment]
oh I see this issue is in PSI... ok
